language: node_js
before_install:
node_js:
  - "6"
before_script:
script:
  - npm run build
  # run build script specified in package.json
  # - npm run gulp build
  # call script for deploying of produced  artifacts
  - bash ./.travis-deploy.sh
